services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: password
    volumes:
      - db_data:/foo

volumes:
  db_data: 
    